apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secrets
  namespace: petclinic
type: Opaque
stringData:
  mysqluser: petclinic
  mysqlpass: 2wbZEbdtHHsUvmMj
  mysqlurl: jdbc:mysql://petclinic.cgz2br1nzzx8.us-east-1.rds.amazonaws.com/petclinic
